// pll.v

// Generated using ACDS version 13.0sp1 232 at 2013.08.18.15:38:03

`timescale 1 ps / 1 ps
module pll (
		output wire        altpll_0_c0_clk,                      //                    altpll_0_c0.clk
		input  wire        altpll_0_pll_slave_read,              //             altpll_0_pll_slave.read
		input  wire        altpll_0_pll_slave_write,             //                               .write
		input  wire [1:0]  altpll_0_pll_slave_address,           //                               .address
		output wire [31:0] altpll_0_pll_slave_readdata,          //                               .readdata
		input  wire [31:0] altpll_0_pll_slave_writedata,         //                               .writedata
		input  wire        altpll_0_inclk_interface_reset_reset, // altpll_0_inclk_interface_reset.reset
		input  wire        altpll_0_inclk_interface_clk,         //       altpll_0_inclk_interface.clk
		input  wire        altpll_0_areset_conduit_export,       //        altpll_0_areset_conduit.export
		output wire        altpll_0_locked_conduit_export,       //        altpll_0_locked_conduit.export
		output wire        altpll_0_phasedone_conduit_export     //     altpll_0_phasedone_conduit.export
	);

	pll_altpll_0 altpll_0 (
		.clk       (altpll_0_inclk_interface_clk),         //       inclk_interface.clk
		.reset     (altpll_0_inclk_interface_reset_reset), // inclk_interface_reset.reset
		.read      (altpll_0_pll_slave_read),              //             pll_slave.read
		.write     (altpll_0_pll_slave_write),             //                      .write
		.address   (altpll_0_pll_slave_address),           //                      .address
		.readdata  (altpll_0_pll_slave_readdata),          //                      .readdata
		.writedata (altpll_0_pll_slave_writedata),         //                      .writedata
		.c0        (altpll_0_c0_clk),                      //                    c0.clk
		.areset    (altpll_0_areset_conduit_export),       //        areset_conduit.export
		.locked    (altpll_0_locked_conduit_export),       //        locked_conduit.export
		.phasedone (altpll_0_phasedone_conduit_export)     //     phasedone_conduit.export
	);

endmodule
